import { mkdirSync, writeFileSync, existsSync } from 'node:fs';
import { join, resolve, basename } from 'node:path';
import { parseFlags } from '../utils.js';
import { detectProject } from '../engine/detect.js';
import { discoverEnvironments } from '../engine/environment.js';
import { extractArchitecture } from '../engine/architecture.js';
import { loadKnowledge } from './learn.js';
import type { DetectedProject } from '../types.js';
import type { DiscoveredEnvironment } from '../engine/environment.js';
import type { DiscoveredService } from '../engine/architecture.js';
import type { KnowledgeEntry } from './learn.js';

// ── Markdown Generation ──────────────────────────────────────────────

function generateProjectMd(
  dir: string,
  detected: DetectedProject,
  environments: DiscoveredEnvironment[],
  services: DiscoveredService[],
  dataFlow: string[] | undefined,
  knowledge: KnowledgeEntry[],
): string {
  const lines: string[] = [];

  // Header
  lines.push(`# ${detected.name}`);
  lines.push('');
  lines.push('> Auto-generated by icex-flow. Re-run `icex-flow generate` to update.');
  lines.push('');

  // ── Project Overview ──
  lines.push('## Project Overview');
  lines.push('');
  lines.push(`| Field | Value |`);
  lines.push(`|-------|-------|`);
  lines.push(`| Name | ${detected.name} |`);
  lines.push(`| Type | ${detected.preset} |`);
  lines.push(`| Language | ${detected.language}${detected.languages.length > 1 ? ` (${detected.languages.join(', ')})` : ''} |`);
  if (detected.repo_url) {
    lines.push(`| Repository | ${detected.repo_url} |`);
  }
  if (detected.ci) {
    lines.push(`| CI/CD | ${detected.ci} |`);
  }
  if (detected.test_command) {
    lines.push(`| Test Command | \`${detected.test_command}\` |`);
  }
  if (detected.build_command) {
    lines.push(`| Build Command | \`${detected.build_command}\` |`);
  }
  lines.push(`| Containerized | ${detected.containerized ? 'Yes' : 'No'} |`);
  lines.push(`| DB Migrations | ${detected.has_db_migrations ? 'Yes' : 'No'} |`);
  if (detected.is_monorepo) {
    lines.push(`| Monorepo | Yes |`);
  }
  lines.push('');

  // ── Environments ──
  const envKnowledge = knowledge.filter(k => k.category === 'environment');
  if (environments.length > 0 || envKnowledge.length > 0) {
    lines.push('## Environments');
    lines.push('');

    if (environments.length > 0) {
      lines.push('| Name | Type | Production | Namespace | Endpoint |');
      lines.push('|------|------|-----------|-----------|----------|');
      for (const env of environments) {
        const prod = env.isProduction ? '**YES**' : 'no';
        lines.push(`| ${env.name} | ${env.type} | ${prod} | ${env.namespace ?? '-'} | ${env.endpoint ?? '-'} |`);
      }
      lines.push('');
    }

    if (envKnowledge.length > 0) {
      lines.push('### Environment Notes');
      lines.push('');
      for (const k of envKnowledge) {
        lines.push(`- ${k.text}`);
      }
      lines.push('');
    }
  }

  // ── Architecture ──
  if (services.length > 0) {
    lines.push('## Architecture');
    lines.push('');
    lines.push('### Services');
    lines.push('');
    lines.push('| Service | Language | Port | Database | Dependencies |');
    lines.push('|---------|----------|------|----------|-------------|');
    for (const svc of services) {
      lines.push(`| ${svc.name} | ${svc.language ?? '-'} | ${svc.port ?? '-'} | ${svc.database ?? '-'} | ${svc.dependencies?.join(', ') ?? '-'} |`);
    }
    lines.push('');

    if (dataFlow && dataFlow.length > 0) {
      lines.push('### Data Flow');
      lines.push('');
      lines.push('```');
      for (const flow of dataFlow) {
        lines.push(flow);
      }
      lines.push('```');
      lines.push('');
    }

    // Add architecture knowledge
    const archKnowledge = knowledge.filter(k => k.category === 'architecture');
    if (archKnowledge.length > 0) {
      lines.push('### Architecture Notes');
      lines.push('');
      for (const k of archKnowledge) {
        lines.push(`- ${k.text}`);
      }
      lines.push('');
    }
  }

  // ── Deployment ──
  if (detected.deployment || detected.ci || detected.containerized) {
    lines.push('## Deployment');
    lines.push('');
    if (detected.deployment) {
      lines.push(`- **Strategy**: ${detected.deployment}`);
    }
    if (detected.ci) {
      lines.push(`- **CI/CD**: ${detected.ci}`);
    }
    if (detected.containerized) {
      lines.push(`- **Containerized**: Yes (Docker)`);
    }

    // GitOps detection
    const argoEnvs = environments.filter(e => e.type === 'argocd');
    const fluxEnvs = environments.filter(e => e.type === 'flux');
    if (argoEnvs.length > 0) {
      lines.push(`- **GitOps**: ArgoCD (${argoEnvs.map(e => e.name).join(', ')})`);
    }
    if (fluxEnvs.length > 0) {
      lines.push(`- **GitOps**: Flux (${fluxEnvs.map(e => e.name).join(', ')})`);
    }

    // Workflow knowledge
    const wfKnowledge = knowledge.filter(k => k.category === 'workflow');
    if (wfKnowledge.length > 0) {
      lines.push('');
      lines.push('### Deployment Notes');
      lines.push('');
      for (const k of wfKnowledge) {
        lines.push(`- ${k.text}`);
      }
    }
    lines.push('');
  }

  // ── Safety Rules ──
  lines.push('## Safety Rules');
  lines.push('');

  // Auto-generated safety rules based on detected environments
  const prodEnvs = environments.filter(e => e.isProduction);
  if (prodEnvs.length > 0) {
    lines.push('### Production Environments');
    lines.push('');
    for (const env of prodEnvs) {
      lines.push(`- **${env.name}** is a production environment — require explicit authorization before any changes`);
    }
    lines.push('- Never deploy untested code to production');
    lines.push('- Always verify changes in a non-production environment first');
    lines.push('');
  }

  if (detected.has_db_migrations) {
    lines.push('- Database migrations must be reviewed before applying to production');
    lines.push('- Always backup the database before running migrations in production');
    lines.push('');
  }

  // Safety knowledge
  const safetyKnowledge = knowledge.filter(k => k.category === 'safety');
  if (safetyKnowledge.length > 0) {
    lines.push('### Project-Specific Safety Rules');
    lines.push('');
    for (const k of safetyKnowledge) {
      lines.push(`- ${k.text}`);
    }
    lines.push('');
  }

  // If no safety rules were generated
  if (prodEnvs.length === 0 && !detected.has_db_migrations && safetyKnowledge.length === 0) {
    lines.push('- No production environments detected — add safety rules with `icex-flow learn`');
    lines.push('');
  }

  // ── Custom Knowledge ──
  const customKnowledge = knowledge.filter(k => k.category === 'custom');
  if (customKnowledge.length > 0) {
    lines.push('## Custom Knowledge');
    lines.push('');
    for (const k of customKnowledge) {
      lines.push(`- ${k.text}`);
    }
    lines.push('');
  }

  // ── Features ──
  if (detected.detected_features.length > 0) {
    lines.push('## Detected Features');
    lines.push('');
    for (const feature of detected.detected_features) {
      lines.push(`- \`${feature}\``);
    }
    lines.push('');
  }

  return lines.join('\n');
}

// ── Command ──────────────────────────────────────────────────────────

/**
 * @param dir - The directory where .icex-flow/ config lives (output target)
 * @param scanPath - Optional remote directory to scan for project detection.
 *                   When provided, detection/discovery reads from scanPath
 *                   but output is written to dir's .icex-flow/.
 */
export function runGenerate(dir: string, scanPath?: string): void {
  const absDir = resolve(dir);
  const flowDir = join(absDir, '.icex-flow');

  // scanDir is where we read project files; absDir is where we write config
  const scanDir = scanPath ? resolve(scanPath) : absDir;

  // 1. Detect project
  console.log(`Detecting project${scanPath ? ` from ${scanDir}` : ''}...`);
  const detected = detectProject(scanDir);

  // 2. Discover environments
  console.log('Discovering environments...');
  const envResult = discoverEnvironments(scanDir);

  // 3. Extract architecture
  console.log('Extracting architecture...');
  const archResult = extractArchitecture(scanDir);

  // 4. Load knowledge (from config dir, not scan dir)
  const knowledge = loadKnowledge(absDir);

  // 5. Generate PROJECT.md
  console.log('Generating PROJECT.md...');
  const projectMd = generateProjectMd(
    absDir,
    detected,
    envResult.environments,
    archResult.services,
    archResult.dataFlow,
    knowledge.entries,
  );

  // 6. Write to context directory
  const projectContextDir = join(flowDir, 'context', 'L1-project', detected.name);
  mkdirSync(projectContextDir, { recursive: true });
  const outputPath = join(projectContextDir, 'PROJECT.md');
  writeFileSync(outputPath, projectMd, 'utf-8');

  console.log('');
  console.log(`Generated: ${outputPath}`);
  console.log('');
  console.log(`  Environments: ${envResult.environments.length} discovered`);
  console.log(`  Services:     ${archResult.services.length} found`);
  console.log(`  Knowledge:    ${knowledge.entries.length} entries`);
  if (archResult.dataFlow && archResult.dataFlow.length > 0) {
    console.log(`  Data flows:   ${archResult.dataFlow.length} connections`);
  }
}

export function cmdGenerate(args: string[]): void {
  const { flags } = parseFlags(args);
  const dir = flags['dir'] ?? '.';
  const scanPath = flags['path'] ?? undefined;

  if (!existsSync(join(resolve(dir), '.icex-flow'))) {
    console.error('Not an icex-flow project. Run "icex-flow init" first.');
    process.exit(1);
  }

  runGenerate(dir, scanPath);
}
